# .streamlit/secrets.toml

# ===============================================
# القسم الأول: مفتاح المساعد الذكي (موجود بالفعل)
# ===============================================
GOOGLE_API_KEY = "AIzaSyCiIlXkwVDiOUrXgNzM4w9-0UQYWmUjPvE"


# ===============================================
# القسم الثاني: مفتاح جوجل (بالتنسيق الصحيح)
# ===============================================
[gcp_service_account]
type = "service_account"
project_id = "amany-health-project"
private_key_id = "f5c368e83a927bc98ed20019ab334738fc0d5d00"
private_key = """-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCY0bts9Jt6woyQ\nmTpZQ//vVB93B6SG0SSuoJP6vnB8V6zskSkvzBcfRyAws6ADlnn2MQEoTBpUbUr9\nR90W0WbWndY8+WUXcjFbp2De2Ay+LPGom/BExn5pAPwMpyu+ABegEtikTUSo0rpa\nOhLNm9V2PJ4UElh5T4ytfUZ1JO66FBRsct2a9d5eZF0Hh7EH6utmyusUL2pp6D7t\n5GXIn0GpDSeje3naqUX7FLT6wyQd4Qltrti7oeYWrf3Ui+jwkx6JQhuNB+BTdZXw\nHUst43R8j0KZN0mg/tl40k5Ivz29GBuuXnHO3azSqgOMrBrzxpdL0M1tVII1jLWn\nM5x+LRLxAgMBAAECggEAHVmMjFq3QL68JepT10CU1zd6Go98dQsWZzZ+bTYlnu/s\nzXt8pEond7GemFPrS70a++JCBWYGWYgrEpV6fA8oF9h1BL1mQbhEDAULuQjX+69g\nk0Atx1uy/AI9JkX2A/X7E5qDAp03blAYi8sjANuoxd5TAupaFSRm0Ywhm86FzfVQ\nvQ9/HqgV7cnB0ZS0M2+Qwa2wE1e6uuJXtTAHw9HrZuXxvDUnxLXvkCyKRqD7EkQf\nQW4Yhwz1/B8qFkWAhA19m3XwnG6u1evulB9/SKeCso5Y/AtR0PZNX7IHcH/rYzFD\n355DWON+w2JcDTGbvvoFHQtM5guqMWefoq6grJoPdQKBgQDPq6PnSs31Um/J7Fo/\nt73Z68DxNmpY9v0gd0wHQm4N2PG6AGbRwsNEUiinxiilbjJdAIc+E9qfv7vRRWRv\nBZQlZNIyAJhpBcEXBkDEEug0tMOPZLFTlXeWVXGSFnK0wT4hJVry6enavz1hcdXS\n67Qme0ELo7HTa0QCYKdgBThodQKBgQC8Yjpff1fKlOiG2vUG8CvYEwhFx8mXkjVR\nfilXJjmEN1HbfoYaJB4yeIn38BJVFppmfX1k7WYGGlAW64LXuYWIIrZlJn26cKBi\nvjuqJBzYyxhCfADJAQapvh4og/j0c7XVzj0+U1mNbK8Yx+rZqoc8FHBqfckZFvmw\nKaAtIeARDQKBgAWhgMs3swfw2UkfWH8by1EKXGvt7spEwC5OLciQm41SkZNaiW8s\nmcDTfXi3HckGiOUOq5waS7ZDK6OL/yIng5HT/wMOExPd7RNjvwPSA2vSbu8Haut6\nRQjVfkPYyflut/GMIsAtaYLd5psqzAJxE6xrcSMQqDS0Vt69oiwvWA01AoGANBx0\nC1C9p1Nz00Ikf8vWRQpWwn7WvC/8wdNFek8fn/xxj2c7j2WoWMvRVp25ZIJBKdLS\n6iVlkJCc0QpLAoPWdWcsz2RLaVSYeVgoRxOAS1Q7HMESsoevIStvSkPfjTeo+ED5\n3hDOd/m1ogRDafzrNeptgnfTNjaN0XZiUbnKMs0CgYAaYBJU3H1cYmwf3tS6yO7y\nc7E7BkDmw6N/pQuC7R1aiDUiro0ycGoN38xKffxgme7vxy47w4URGoxfOlTTSdjG\nPR5GCBGIjV0iYF7OsC62K2S/tDmxLdM4PtXkLwypVBKkN/OvWYmIQb49QImXSuI0\nkc0MMIddqbGOzBoGEjjn3w==\n-----END PRIVATE KEY-----\n"""
client_email = "amany-data-reader@amany-health-project.iam.gserviceaccount.com"
client_id = "106881876457737424195"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/amany-data-reader%40amany-health-project.iam.gserviceaccount.com"
[sheets]
spreadsheet_id = "1lELs2hhkOnFVix8HSE4iHpw8r20RXnEMXK9uzHSbT6Y"

